# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'LingoBook' do
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'ChameleonFramework/Swift'
end

target 'LingoBookTests' do

end

target 'LingoBookUITests' do

end
